config/routes.rb
Rails.application.routes.draw do
  
  #resource :users

  root 'home#index'

  devise_for :users, :controllers => { registrations: 'users/registrations' ,sessions: 'users/sessions'}
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resource :users, :only => [:show]    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	
 	geocoded_by :address
  	reverse_geocoded_by :latitude, :longitude 
	after_validation :geocode, :if => :address_changed?





  	validates :address, presence: true
	validates :avatar, attachment_presence: true
	#has_attached_file :avatar, styles: { medium: "300x300>", thumb: "40x40>" }, default_url: "/images/:style/missing.png"


	if Rails.env.production?
  	has_attached_file :avatar,
		  :storage => :s3,
		  :s3_credentials => "#{Rails.root}/config/s3.yml",
		  :path => "/:class/avatars/:id/:style/:filename",
		  :url => ":s3_domain_url",
		  :styles => {medium: "300x300>", thumb: "40x40>"}
	else
		  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "40x40>" }, default_url: "/images/:style/missing.png"
	end
  
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  	def city
  	   address = Geocoder.search("#{self.latitude},#{self.longitude}").first
       city = address.present? ? address.city : ""
  	end
    def country
       address = Geocoder.search("#{self.latitude},#{self.longitude}").first
       country = address.present? ? address.country : ""
    end

    def avatar_url
        self.avatar.url(:thumb)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :users

  def after_sign_in_path_for(resourse)
    root_path
  end

 
  private
 
  def users
    @users = User.all
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:address,:avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  

	def index
    @data = User.all.as_json(:only=>[:id,:email,:latitude,:longitude],:methods=>[:city,:country,:avatar_url]).to_json
	end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def show
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
.row
  .col-md-12.top40
    %h1.text-xs-center Welcome to Google Map Application
  
.map-container
  .row#map 
.ct-btn.text-xs-center= button_tag "click here to Zoom/Pan on & off",id:'ct-btn',class:'btn btn-primary'

- content_for :javascript do
  :javascript
    var data = #{@data}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Google Map Application"
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "Google Map Application"}", :name => "description"}/
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_map_key}"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :javascript

  %body{:class => "#{controller_name} #{action_name}"}
    .container  
      %nav.navbar.navbar-dark.bg-inverse= render 'shared/header'
      = render 'layouts/messages'
      = yield
      

app/views/layouts/navigation_links.html.haml
%ul
	%li= link_to 'Home', root_path

app/views/shared/_footer.html.haml
%copyright
  \© Google Map Appllication #{Time.now.year}
%nav
  %ul
    %li= link_to "About",   root_path
    %li= link_to "Contact", root_path
    %li
      %a{:href => "http://news.railstutorial.org/"} News

app/views/shared/_header.html.haml
- users_count = @users.present? ? @users.size : 0

%ul.nav.navbar-nav

  %li= link_to "Home(#{users_count})", root_path,class:'navbar-brand','data-turbolinks':false
  - unless current_user
    %li=# link_to 'About us', '#',class:'navbar-brand'
    %li= link_to 'Sign up', new_user_registration_path,class:'navbar-brand float-xs-right'
    %li= link_to 'Sign in', new_user_session_path,class:'navbar-brand float-xs-right'
  - else
    %li= link_to 'Sing out', destroy_user_session_path, method:'delete',class:'navbar-brand float-xs-right'

app/views/users/_infowindow.html.haml
= object.email

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/